capawesome-team/capacitor-plugins

- .changeset/little-jobs-smoke.md
- packages/app-update/BREAKING.md
- packages/app-update/README.md
- packages/app-update/android/build.gradle
> refactor(app-update)!: rename project variable `androidPlayCore` to `androidPlayCoreVersion`

- .changeset/shaggy-planes-smash.md
- packages/file-picker/src/web.ts
> feat(file-picker): add web support for `pickImages(...)`, `pickMedia(…)` and `pickVideos(...)`

- package-lock.json
- packages/app-update/package.json
- packages/background-task/package.json
- packages/badge/package.json
- packages/cloudinary/package.json
- packages/datetime-picker/package.json
- packages/file-opener/package.json
- packages/file-picker/package.json
- packages/managed-configurations/package.json
- packages/photo-editor/package.json
- packages/screen-orientation/package.json
> chore(deps): remove `standard-version`

- .prettierrc.js
- package-lock.json
- packages/app-update/.prettierrc.js
- packages/app-update/package.json
- packages/background-task/.prettierrc.js
- packages/background-task/package.json
- packages/badge/.prettierrc.js
- packages/badge/package.json
- packages/cloudinary/.prettierrc.js
- packages/cloudinary/package.json
- packages/datetime-picker/.prettierrc.js
- packages/datetime-picker/package.json
- packages/file-opener/.prettierrc.js
- packages/file-opener/package.json
- packages/file-picker/.prettierrc.js
- packages/file-picker/package.json
- packages/managed-configurations/.prettierrc.js
- packages/managed-configurations/package.json
- packages/photo-editor/.prettierrc.js
- packages/photo-editor/package.json
- packages/screen-orientation/.prettierrc.js
- packages/screen-orientation/package.json
> chore: fix error `[error] No parser could be inferred for file *.java`

- .changeset/big-roses-nail.md
- packages/datetime-picker/ios/Plugin/RPicker.swift
- packages/file-opener/README.md
- packages/file-opener/android/build.gradle
- packages/file-opener/android/src/main/AndroidManifest.xml
- packages/file-opener/android/src/main/java/io/capawesome/capacitorjs/plugins/fileopener/FileOpener.java
- packages/file-opener/android/src/main/java/io/capawesome/capacitorjs/plugins/fileopener/FileOpenerPlugin.java
- packages/file-opener/android/src/main/java/io/capawesome/capacitorjs/plugins/fileopener/FileOpenerProvider.java
- packages/file-opener/android/src/main/res/xml/filepaths.xml
- packages/screen-orientation/ios/Plugin/ScreenOrientation.swift
> fix(file-opener): returns `File does not exist` although file exists

- .changeset/late-timers-sleep.md
- packages/app-update/README.md
- packages/app-update/android/build.gradle
- packages/app-update/android/src/main/java/io/capawesome/capacitorjs/plugins/appupdate/AppUpdatePlugin.java
> fix(app-update): replace `com.google.android.play:core` as dependency on Android

- .changeset/fifty-hats-sparkle.md
- packages/file-opener/android/src/main/java/io/capawesome/capacitorjs/plugins/fileopener/FileOpenerPlugin.java
> fix(file-opener): check if file can be opened on Android

- .changeset/fast-seahorses-decide.md
- packages/file-opener/README.md
- packages/file-opener/android/src/main/java/io/capawesome/capacitorjs/plugins/fileopener/FileOpenerPlugin.java
Close #63
See https://stackoverflow.com/a/65823629/6731412
> fix(file-opener): remove `resolveActivity` check

- .changeset/mean-maps-shop.md
- packages/cloudinary/README.md
- packages/cloudinary/android/src/main/java/io/capawesome/capacitorjs/plugins/cloudinary/CloudinaryHelper.java
- packages/cloudinary/docs/utils/README.md
- packages/cloudinary/ios/Plugin/CloudinaryHelper.swift
- packages/cloudinary/src/definitions.ts
- packages/cloudinary/src/utils.ts
> feat(cloudinary): add `secure_url` property

- .changeset/poor-camels-poke.md
- packages/file-picker/ios/Plugin/FilePicker.swift
- packages/file-picker/ios/Plugin/FilePickerPlugin.swift
> fix(file-picker): copy picked files to unique directories on iOS

- .changeset/polite-vans-cry.md
- packages/datetime-picker/android/src/main/java/io/capawesome/capacitorjs/plugins/datetimepicker/DatetimePicker.java
> fix(datetime-picker): missing null check

- .changeset/wise-ears-judge.md
- packages/file-opener/ios/Plugin/FileOpener.swift
- packages/file-opener/ios/Plugin/FileOpenerPlugin.swift
> fix(file-opener): throw an error if the file could not be opened

- .changeset/nervous-dancers-change.md
- packages/file-picker/README.md
- packages/file-picker/ios/Plugin/FilePicker.swift
- packages/file-picker/ios/Plugin/FilePickerPlugin.swift
- packages/file-picker/src/definitions.ts
…ly) #114
- boolean ordered added in ios swift
- checked for ios >= 15
- definition update
- fmt
- docgen
- changeset
> feat(file-picker): add `ordered` option

- .changeset/three-walls-double.md
- packages/app-update/android/src/main/java/io/capawesome/capacitorjs/plugins/appupdate/AppUpdatePlugin.java
> fix(app-update): replace deprecated method

- .changeset/olive-mugs-provide.md
- packages/file-picker/BREAKING.md
- packages/file-picker/README.md
- packages/file-picker/android/src/main/java/io/capawesome/capacitorjs/plugins/filepicker/FilePickerPlugin.java
- packages/file-picker/ios/Plugin/FilePicker.swift
- packages/file-picker/ios/Plugin/FilePickerPlugin.swift
- packages/file-picker/src/definitions.ts
- packages/file-picker/src/web.ts
> feat(file-picker): replace `multiple` option with `limit`

- .changeset/blue-rocks-ring.md
- packages/cloudinary/README.md
- packages/cloudinary/docs/utils/README.md
- packages/cloudinary/ios/Plugin/CloudinaryHelper.swift
- packages/cloudinary/src/definitions.ts
See https://github.com/cloudinary/cloudinary_ios/issues/399#issuecomment-1776606391
Close #5
> feat(cloudinary): make bytes available on iOS

- .changeset/gold-buckets-joke.md
- packages/app-update/BREAKING.md
- packages/app-update/android/src/main/java/io/capawesome/capacitorjs/plugins/appupdate/AppUpdatePlugin.java
- packages/app-update/ios/Plugin/AppUpdatePlugin.swift
- packages/app-update/src/definitions.ts
- packages/file-picker/BREAKING.md
> refactor(app-update): remove `currentVersion` and `availableVersion` properties

- .changeset/lucky-onions-wait.md
- packages/file-picker/BREAKING.md
- packages/file-picker/src/definitions.ts
- packages/file-picker/src/web.ts
> refactor(file-picker)!: remove `File` interface

- .changeset/stupid-clouds-search.md
- packages/file-picker/BREAKING.md
- packages/file-picker/ios/Plugin/FilePickerPlugin.swift
- packages/file-picker/src/definitions.ts
> refactor(file-picker): default value for `skipTranscoding` is now `true`

- .changeset/tidy-cycles-admire.md
- packages/cloudinary/CapawesomeCapacitorCloudinary.podspec
- packages/cloudinary/ios/Podfile
> chore(cloudinary): update Cloudinary iOS SDK to `5.0.0`

- .changeset/new-adults-drop.md
- packages/android-foreground-service/android/src/main/java/io/capawesome/capacitorjs/plugins/foregroundservice/ForegroundServicePlugin.java
> fix(android-foreground-service): invalid property name returned on Android

- .changeset/short-masks-tell.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/ios/Plugin/LiveUpdate.swift
> fix(live-update): `setBundle` is not resolved 

- .changeset/breezy-planes-thank.md
- packages/live-update/ios/Plugin/LiveUpdate.swift
> fix(live-update): improve unzip performance on iOS

- .changeset/stale-phones-buy.md
- packages/file-opener/src/definitions.ts
- packages/file-opener/src/web.ts
> feat(file-opener): add web support

- .changeset/few-toes-return.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/ios/Plugin/LiveUpdate.swift
> fix(live-update): `reset()` followed by `reload()` did not load the built-in bundle

- .changeset/sour-melons-teach.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/ios/Plugin/LiveUpdate.swift
> chore(live-update): print debug url on sync

- .changeset/gold-shirts-eat.md
- packages/file-picker/ios/Plugin/FilePicker.swift
> bug(file-picker): on ios - wrong selection order #213

- .changeset/odd-comics-carry.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/api/GetLatestBundleResponse.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/options/DownloadBundleOptions.java
- packages/live-update/ios/Plugin/Classes/CustomError.swift
- packages/live-update/ios/Plugin/Classes/Options/DownloadBundleOptions.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/ios/Plugin/Protocols/Api/GetLatestBundleResponse.swift
- packages/live-update/src/definitions.ts
> feat(live-update): add support for checksum verification

- .changeset/small-goats-clean.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdateConfig.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdateConfig.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/src/definitions.ts
> feat(live-update): add `location` configuration option

- .changeset/moody-pumas-attack.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdateConfig.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdateConfig.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/src/definitions.ts
> feat(live-update): add `defaultChannel` configuration option

- .changeset/moody-lobsters-attend.md
- packages/live-update/ios/Plugin/LiveUpdate.swift
> fix(live-update): update possibly failed if more than one `index.html` file exists

- .changeset/eleven-icons-speak.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/ios/Plugin/Classes/CustomError.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
> fix(live-update): throw an error if the sync is already in progress

- .changeset/funny-trainers-tap.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/ios/Plugin/Classes/CustomError.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
> fix(live-update): throw error if a http timeout occurs

- .changeset/smooth-wolves-boil.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
> fix(live-update): perform a reset when the current bundle is deleted

- .changeset/three-wasps-lie.md
- packages/file-picker/android/src/main/java/io/capawesome/capacitorjs/plugins/filepicker/FilePickerPlugin.java
> fix(file-picker): no files were returned on Android 10 and below with the Samsung Gallery app

- .changeset/hot-spoons-yell.md
- packages/file-picker/README.md
- packages/file-picker/android/src/main/java/io/capawesome/capacitorjs/plugins/filepicker/FilePickerPlugin.java
- packages/file-picker/src/definitions.ts
- packages/file-picker/src/web.ts
Close https://github.com/capawesome-team/capacitor-plugins/issues/297
Close https://github.com/capawesome-team/capacitor-plugins/pull/299
Close #293
> feat: add `checkPermissions()` and `requestPermissions(...)` methods

- .changeset/orange-rings-call.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/results/FetchLatestBundleResult.java
- packages/live-update/ios/Plugin.xcodeproj/project.pbxproj
- packages/live-update/ios/Plugin/Classes/Results/FetchLatestBundle.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.m
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/src/definitions.ts
- packages/live-update/src/web.ts
> feat(live-update): add `fetchLatestBundle()` method

- .changeset/gold-scissors-clap.md
- packages/app-review/README.md
- packages/app-review/android/build.gradle
- packages/app-review/android/src/main/java/io/capawesome/capacitorjs/plugins/appreview/AppReview.java
- packages/app-review/android/src/main/java/io/capawesome/capacitorjs/plugins/appreview/AppReviewPlugin.java
- packages/app-review/android/src/main/java/io/capawesome/capacitorjs/plugins/appreview/Callback.java
- packages/app-review/android/src/main/java/io/capawesome/capacitorjs/plugins/appreview/EmptyCallback.java
- packages/app-review/android/src/main/java/io/capawesome/capacitorjs/plugins/appreview/ReviewResultCallback.java
- packages/app-review/ios/Plugin/AppReview.swift
- packages/app-review/ios/Plugin/AppReviewPlugin.m
- packages/app-review/ios/Plugin/AppReviewPlugin.swift
- packages/app-review/src/definitions.ts
- packages/app-review/src/web.ts
> App review plugin

- .changeset/hip-emus-attack.md
- packages/torch/README.md
- packages/torch/android/build.gradle
- packages/torch/android/src/main/java/io/capawesome/capacitorjs/plugins/torch/Torch.java
- packages/torch/src/definitions.ts
> feat(torch): add support for ML Kit Barcode Scanning

- .changeset/serious-rocks-fold.md
- packages/app-review/README.md
- packages/app-review/example/src/js/capacitor-welcome.js
- packages/app-review/ios/Plugin.xcodeproj/project.pbxproj
- packages/app-review/ios/Plugin/AppReview.swift
- packages/app-review/ios/Plugin/AppReviewPlugin.swift
- packages/app-review/ios/Plugin/Classes/Options/OpenAppStoreOptions.swift
- packages/app-review/ios/Plugin/Enums/CustomError.swift
- packages/app-review/src/definitions.ts
> fix(app-review): `openAppStore()` missing `appId` on iOS

- .changeset/fair-countries-fetch.md
- packages/app-update/README.md
- packages/app-update/ios/Plugin/AppUpdatePlugin.swift
- packages/app-update/src/definitions.ts
> feat(app-update): add `appId` property to `OpenAppStoreOptions`

- package-lock.json
- packages/app-shortcut/README.md
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/AppShortcut.java
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/AppShortcutHelper.java
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/AppShortcutPlugin.java
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/classes/options/SetOptions.java
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/classes/results/GetResult.java
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/interfaces/Callback.java
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/interfaces/EmptyCallback.java
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/interfaces/NonEmptyCallback.java
- packages/app-shortcut/android/src/main/java/io/capawesome/capacitorjs/plugins/appshortcut/interfaces/Result.java
- packages/app-shortcut/ios/Plugin.xcodeproj/project.pbxproj
- packages/app-shortcut/ios/Plugin/AppShortcut.swift
- packages/app-shortcut/ios/Plugin/AppShortcutPlugin.m
- packages/app-shortcut/ios/Plugin/AppShortcutPlugin.swift
- packages/app-shortcut/ios/Plugin/Classes/Options/SetOptions.swift
- packages/app-shortcut/ios/Plugin/Classes/Results/GetResult.swift
- packages/app-shortcut/ios/Plugin/Enums/CustomError.swift
- packages/app-shortcut/ios/Plugin/Protocols/Result.swift
- packages/app-shortcut/package.json
- packages/app-shortcut/src/definitions.ts
> feat(app-shortcut): add implementation

- .changeset/gold-ears-float.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/options/FetchLatestBundleOptions.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/options/SyncOptions.java
- packages/live-update/ios/Plugin.xcodeproj/project.pbxproj
- packages/live-update/ios/Plugin/Classes/Options/FetchLatestBundleOptions.swift
- packages/live-update/ios/Plugin/Classes/Options/SyncOptions.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/src/definitions.ts
> feat(live-update): add a `channel` option to `sync()` and `fetchLatestBundle()` methods

- .changeset/popular-nails-roll.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/api/GetLatestBundleResponse.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/results/FetchLatestBundleResult.java
- packages/live-update/ios/Plugin/Classes/Results/FetchLatestBundle.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/src/definitions.ts
> feat(live-update): add `downloadUrl` property to `FetchLatestBundleResult`

- .changeset/flat-gifts-check.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/results/GetCurrentBundleResult.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/results/GetNextBundleResult.java
- packages/live-update/ios/Plugin.xcodeproj/project.pbxproj
- packages/live-update/ios/Plugin/Classes/Results/GetCurrentBundleResult.swift
- packages/live-update/ios/Plugin/Classes/Results/GetNextBundleResult.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.m
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/src/definitions.ts
- packages/live-update/src/web.ts
> feat(live-update): add `getCurrentBundle()` and `getNextBundle()` methods

- .changeset/tame-icons-search.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/options/SetNextBundleOptions.java
- packages/live-update/ios/Plugin.xcodeproj/project.pbxproj
- packages/live-update/ios/Plugin/Classes/Options/SetNextBundleOptions.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.m
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/src/definitions.ts
- packages/live-update/src/web.ts
> feat(live-update): add `setNextBundle()` methods

- package-lock.json
- packages/screenshot/README.md
- packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/Screenshot.java
- packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/ScreenshotHelper.java
- packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/ScreenshotPlugin.java
- packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/classes/interfaces/Callback.java
- packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/classes/interfaces/NonEmptyCallback.java
- packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/classes/interfaces/Result.java
- packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/classes/results/TakeResult.java
- packages/screenshot/ios/Plugin.xcodeproj/project.pbxproj
- packages/screenshot/ios/Plugin/Classes/Enums/CustomError.swift
- packages/screenshot/ios/Plugin/Classes/Protocols/Result.swift
- packages/screenshot/ios/Plugin/Classes/Results/TakeResult.swift
- packages/screenshot/ios/Plugin/Screenshot.swift
- packages/screenshot/ios/Plugin/ScreenshotPlugin.m
- packages/screenshot/ios/Plugin/ScreenshotPlugin.swift
- packages/screenshot/package.json
- packages/screenshot/src/definitions.ts
- packages/screenshot/src/web.ts
> feat(screenshot): add implementation

- .changeset/odd-wombats-provide.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/api/GetLatestBundleResponse.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/results/FetchLatestBundleResult.java
- packages/live-update/ios/Plugin.xcodeproj/project.pbxproj
- packages/live-update/ios/Plugin/Classes/Results/FetchLatestBundleResult.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/Protocols/Api/GetLatestBundleResponse.swift
- packages/live-update/src/definitions.ts
> feat(live-update): add `customProperties` property to `FetchLatestBundleResult`

- .changeset/wise-avocados-enjoy.md
- packages/live-update/Package.swift
> refactor(live-update): update version for `ZipArchive` dependency in SPM

- .changeset/big-points-approve.md
- packages/posthog/android/src/main/java/io/capawesome/capacitorjs/plugins/posthog/Posthog.kt
- packages/posthog/android/src/main/java/io/capawesome/capacitorjs/plugins/posthog/PosthogPlugin.java
- packages/posthog/android/src/main/java/io/capawesome/capacitorjs/plugins/posthog/classes/options/GetFeatureFlagOptions.java
- packages/posthog/android/src/main/java/io/capawesome/capacitorjs/plugins/posthog/classes/options/IsFeatureEnabledOptions.java
- packages/posthog/android/src/main/java/io/capawesome/capacitorjs/plugins/posthog/classes/results/GetFeatureFlagResult.java
- packages/posthog/android/src/main/java/io/capawesome/capacitorjs/plugins/posthog/classes/results/IsFeatureEnabledResult.java
- packages/posthog/android/src/main/java/io/capawesome/capacitorjs/plugins/posthog/interfaces/Result.java
- packages/posthog/ios/Plugin.xcodeproj/project.pbxproj
- packages/posthog/ios/Plugin/Classes/Options/GetFeatureFlagOptions.swift
- packages/posthog/ios/Plugin/Classes/Options/IsFeatureEnabledOptions.swift
- packages/posthog/ios/Plugin/Classes/Results/GetFeatureFlagResult.swift
- packages/posthog/ios/Plugin/Classes/Results/IsFeatureEnabledResult.swift
- packages/posthog/ios/Plugin/Enums/CustomError.swift
- packages/posthog/ios/Plugin/Posthog.swift
- packages/posthog/ios/Plugin/PosthogHelper.swift
- packages/posthog/ios/Plugin/PosthogPlugin.swift
- packages/posthog/ios/Plugin/Protocols/Result.swift
- packages/posthog/src/definitions.ts
- packages/posthog/src/web.ts
> feat(posthog): support feature flags

- .changeset/serious-gorillas-enjoy.md
- packages/cloudinary/BREAKING.md
- packages/cloudinary/CapawesomeCapacitorCloudinary.podspec
- packages/cloudinary/Package.swift
- packages/cloudinary/README.md
- packages/cloudinary/android/build.gradle
- packages/cloudinary/ios/Podfile
- packages/posthog/BREAKING.md
- packages/posthog/CapawesomeCapacitorPosthog.podspec
- packages/posthog/Package.swift
- packages/posthog/README.md
- packages/posthog/android/build.gradle
- packages/posthog/ios/Plugin/Classes/Options/GetFeatureFlagOptions.swift
- packages/posthog/ios/Plugin/Classes/Options/IsFeatureEnabledOptions.swift
- packages/posthog/ios/Plugin/Posthog.swift
- packages/posthog/ios/Plugin/PosthogPlugin.swift
- packages/posthog/ios/Podfile
> chore: update native dependencies

- .changeset/spotty-jars-agree.md
- packages/live-update/README.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdateHttpClient.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/events/DownloadBundleProgressEvent.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/interfaces/DownloadProgressCallback.java
- packages/live-update/example/src/js/script.js
- packages/live-update/ios/Plugin.xcodeproj/project.pbxproj
- packages/live-update/ios/Plugin/Classes/Events/DownloadBundleProgressEvent.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdateHttpClient.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/src/definitions.ts
> feat(live-update): add `downloadBundleProgress` listener

- .changeset/short-fishes-knock.md
- packages/app-review/Package.swift
- packages/app-shortcuts/Package.swift
- packages/app-update/Package.swift
- packages/background-task/Package.swift
- packages/badge/Package.swift
- packages/cloudinary/Package.swift
- packages/datetime-picker/Package.swift
- packages/file-opener/Package.swift
- packages/file-picker/Package.swift
- packages/managed-configurations/Package.swift
- packages/photo-editor/Package.swift
- packages/posthog/Package.swift
- packages/screen-orientation/Package.swift
- packages/screenshot/Package.swift
- packages/torch/Package.swift
> fix: set correct target paths for SPM support

- .changeset/quiet-apes-relax.md
- packages/android-foreground-service/README.md
- packages/android-foreground-service/android/src/main/java/io/capawesome/capacitorjs/plugins/foregroundservice/AndroidForegroundService.java
> fix(android-foreground-service): `serviceType` property was ignored

- .changeset/grumpy-poets-beam.md
- packages/torch/android/src/main/java/io/capawesome/capacitorjs/plugins/torch/TorchPlugin.java
> fix(torch): calls have not been resolved on Android

- .changeset/quick-days-count.md
- packages/android-edge-to-edge-support/README.md
- packages/android-edge-to-edge-support/android/src/main/java/io/capawesome/capacitorjs/plugins/androidedgetoedgesupport/EdgeToEdge.java
- packages/android-edge-to-edge-support/android/src/main/java/io/capawesome/capacitorjs/plugins/androidedgetoedgesupport/EdgeToEdgeConfig.java
- packages/android-edge-to-edge-support/android/src/main/java/io/capawesome/capacitorjs/plugins/androidedgetoedgesupport/EdgeToEdgePlugin.java
- packages/android-edge-to-edge-support/src/definitions.ts
> feat: Android Edge-to-Edge styling options

- package-lock.json
- packages/live-update/CHANGELOG.md
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdatePlugin.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/api/GetLatestBundleResponse.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/options/DownloadBundleOptions.java
- packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/classes/results/FetchLatestBundleResult.java
- packages/live-update/example/capacitor.config.json
- packages/live-update/example/package-lock.json
- packages/live-update/example/package.json
- packages/live-update/example/src/index.html
- packages/live-update/example/src/js/script.js
- packages/live-update/ios/Plugin/Classes/Options/DownloadBundleOptions.swift
- packages/live-update/ios/Plugin/Classes/Results/FetchLatestBundle.swift
- packages/live-update/ios/Plugin/LiveUpdate.swift
- packages/live-update/ios/Plugin/LiveUpdatePlugin.swift
- packages/live-update/ios/Plugin/LiveUpdatePreferences.swift
- packages/live-update/ios/Plugin/Protocols/Api/GetLatestBundleResponse.swift
- packages/live-update/package.json
- packages/live-update/src/definitions.ts
> feat(live-update): support code signing for self-hosted bundles

- .changeset/wicked-drinks-lay.md
- packages/live-update/CapawesomeCapacitorLiveUpdate.podspec
Hi Robin!
Thanks for your effort working on Capacitor ecosystem! 🙏 
I am using `@capawesome/capacitor-live-update` and `@capgo/capacitor-social-login`. Recently I want to update `@capgo/capacitor-social-login` to latest version, but I am facing problem with `Alamofire` version. 
> refactor(live-update): update version for Alamofire

- .changeset/large-jars-think.md
- package-lock.json
- packages/realtimekit/Package.swift
- packages/realtimekit/example/ios/App/App.xcodeproj/project.pbxproj
- packages/realtimekit/example/package-lock.json
> bug(realtimekit): GH workflow fails

- packages/badge/src/definitions.ts
> fix(badge): lint issues
